INSERT INTO manicure_client (clt_name,
                             clt_surname,
                             clt_phone_number,
                             clt_email,
                             clt_customer_review,
                             clt_amount_spent,
                             clt_discount)
VALUES
    ('Иван',
     'Иванов',
     89999999996,
     'ivanov@example.com',
     'Хороший клиент, всегда доволен',
     1500,
     10),

    ('Мария',
     'Петрова',
     89998888886,
     'petrova@example.com',
     'Очень внимательна к деталям, постоянный клиент',
     2000,
     15),

    ('Алексей',
     'Сидоров',
     89997777776,
     'sidorov@example.com',
     'Рекомендует нас друзьям',
     1000,
     5),

    ('Инна',
     'Маринна',
     89997777776,
     'inka@example.com',
     'Рекомендует',
     5000,
     10);